### ISSUE TITLE
Return Cheating While Get Music URL

### ISSUE THREAD

**Issue by a632079** [surmon-china/simple-netease-cloud-music#6]
RT.
Like: https://api.a632079.me/nm/url/28828371
https://github.com/a632079/teng-koa
```
{
  "code": -460,
  "msg": "Cheating"
}
```

**Comment by a632079** [comment]
I found out why it failed. https://github.com/metowolf/Meting/issues/39 and https://github.com/metowolf/Meting/wiki/special-for-netease
I will do a fork to fix it

**Comment by surmon-china** [comment]
The issue has already been solved.

**Comment by a632079** [comment]
Thanks a lot





------------------ 原始邮件 ------------------
发件人: "Surmon"<notifications@github.com>;
发送时间: 2018年2月23日(星期五) 凌晨1:12
收件人: "surmon-china/simple-netease-cloud-music"<simple-netease-cloud-music@noreply.github.com>;
抄送: "Jonson Petard"<a632079@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [surmon-china/simple-netease-cloud-music] Return Cheating WhileGet Music URL (#6)




The issue has already been solved.
